name: Build and Deploy
on: 
  push:
    branch:
      - main

jobs:
  build-deploy:
    name: Build and Deploy Spring boot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setuup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17
          
      - name: Unit Tests
        run: mvn -B test --file pom.xml

      - name: Build App
        run: |
          mvn clean
          mvn -B package --file pom.xml
